[package]
name = "network"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2024"

[dependencies]
nalgebra = "0.33"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }

[dependencies.shared]
path = "../shared"
