[package]
name = "shared"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2024"

[dependencies]
nalgebra = { version = "0.33", features = ["serde-serialize"] }
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
